
import { checkbox } from '@inquirer/prompts';
import MarkdownRenderer from '../lib/renderer.js';
import i18n from '../services/i18n.js';

/**
 * commits added files
 * * @param {Object} repo - Git repository instance
 * @param {string} message - Message generated by the LLM
 * @returns {Promise<void>}
 * @throws {Error} If git add operation fails
 */
export async function gitCommit(repo, message) {
  try {
    const output = await repo.commit(message);
    console.log(output);
  } catch (error) {
    console.error(i18n.t('output.prefixes.error'), error.message);
    throw error;
  }
}

